language: julia
julia:
  - nightly
  - 1.6

notifications:
  email: false

after_success:
- julia -e 'using Pkg; cd(Pkg.dir("EGPG")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

